import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing env vars.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function generate() {
  const { data, error } = await supabase.auth.admin.generateLink({
    type: 'magiclink',
    email: 'testingevil0@gmail.com',
    options: {
      redirectTo: 'http://localhost:3000/dashboard'
    }
  });

  if (error) {
    console.error('Error generating magic link:', error);
    return;
  }

  // The link generated by Supabase might have the remote URL, but we want it to hit localhost.
  // The link shape is typically: https://<project>.supabase.co/auth/v1/verify?token=...&type=magiclink&redirect_to=http://localhost:3000/dashboard
  // Actually, we can just use the properties in data.properties.action_link!
  const actionLink = data.properties?.action_link;
  console.log('Action Link URL:', actionLink);
}

generate().catch(console.error);
